export default {
    sys_common_dict : 'sys/dict/list',
    sys_common_dict_item : '/sys/dictItem/list',
    sys_common_upload : '/sys/common/upload',
    sys_user_query_list: '/sys/user/list',
    sys_user_change_pwd : '/sys/user/changPassword',
    sys_user_delete : '/sys/user/delete',
    sys_user_deleteBatch : '/sys/user/deleteBatch',
    sys_user_frozenBatch : '/sys/user/frozenBatch',
    sys_user_unique_user_check : '/sys/user/checkOnlyUser',
    sys_user_generate_user_id : '/sys/user/generateUserId',
    sys_user_add_user_dept_ids : '/sys/user/addUDepartIds',
    sys_user_export : '/sys/user/exportXls',
    sys_user_import : '/sys/user/importExcel',
    sys_user_add : '/sys/user/add',
    sys_user_edit : '/sys/user/edit',
    sys_role_query_all: '/sys/role/queryall',
    sys_role_query_user_role : '/sys/user/queryUserRole',
    sys_role_query_list : 'sys/role/list',
    sys_role_query_tree_list : '/sys/role/queryTreeList',
    sys_role_query_permission_by_role : '/sys/permission/queryRolePermission',
    sys_role_save_permission_by_role : '/sys/permission/saveRolePermission',
    sys_role_data_rule : '/sys/role/datarule',
    sys_role_export : '/sys/role/exportXls',
    sys_role_import : '/sys/role/importExcel',
    sys_role_add : '/sys/role/add',
    sys_role_delete_batch : '/sys/role/deleteBatch',
    sys_role_update : '/sys/role/edit',
    sys_dept_query_all : '/sysdepart/sysDepart/queryTreeList',
    sys_dept_query_by_user : '/sys/user/userDepartList',
    sys_dept_add : '/sysdepart/sysDepart/add',
    sys_dept_edit : '/sysdepart/sysDepart/edit',
    sys_dept_export : '/sysdepart/sysDepart/exportXls',
    sys_dept_import : '/sysdepart/sysDepart/importExcel',
    sys_dept_delete_batch : '/sysdepart/sysDepart/deleteBatch',
    sys_dict_unique_check : '/sys/duplicate/check',
    sys_menu_query_list: '/sys/permission/list',
    sys_menu_delete_batch : '/sys/permission/deleteBatch',
    sys_menu_add : '/sys/permission/add'
}
