export default {
    dialog : {
        title : '',
        name : 'modal',
        showFooter : false,
        loading : false,
        clickToClose : false,
        fullScreen : false,
        visible : false,
        resizable : true,
        pivotX : 0.5,
        pivotY : 0.5,
        width : '50',
        height : '50',
        reset : true,
        minWidth : 300,
        minHeight : 300,
        maxHeight : 800,
    },
    table : {
        border: true,
        stripe: true,
        index: true,
        page: true,
        menu: false,
        addBtn: false,
        columnBtn: false,
        menuBtn : false,
        refreshBtn: false,
        selection : true,
        align: 'center',
    }
}