export default {
    online_form_head_query_list : '/online/cgform/head/list',
    online_form_head_delete_batch : '/online/cgform/head/deleteBatch',
    online_form_head_copy_view : '/online/cgform/head/copyOnline',
    online_form_head_delete : '/online/cgform/head/delete',
    online_form_head_remove : '/online/cgform/head/removeRecord',
    online_form_head_table_info : '/online/cgform/head/tableInfo',
    online_form_code_generate : '/online/cgform/api/codeGenerate',
    online_form_head_root_file_fold_list: '/online/cgform/head/rootFile',
    online_form_head_file_fold_list: '/online/cgform/head/fileTree',
    online_form_head_query_by_id : '/online/cgform/field/listByHeadId',
    online_form_index_query_by_id : '/online/cgform/index/listByHeadId',
    online_form_edit : '/online/cgform/api/editAll',
    online_form_add : '/online/cgform/api/addAll',
    online_form_head_js_enhance : '/online/cgform/head/enhanceJs',
    online_form_head_java_enhance : '/online/cgform/head/enhanceJava',
    online_form_table_name_check : '/online/cgform/api/checkOnlyTable',
    online_form_button_custom_query : '/online/cgform/button/list/',
    online_form_button_custom_add : '/online/cgform/button/add',
    online_form_button_custom_edit : '/online/cgform/button/edit',
    online_form_head_form_import_from_db_query : '/online/cgform/head/queryTables/',
    online_form_head_trans_table : '/online/cgform/head/transTables',
    online_form_db_sync : '/online/cgform/api/doDbSynch',
    online_form_auto_online_form_get_columns : '/online/cgform/api/getColumns',
    online_form_auto_online_form_get_datas : '/online/cgform/api/getData',
    online_form_auto_online_form_get_query_info : '/online/cgform/api/getQueryInfo',
    online_report_head_list_query : '/online/cgreport/head/list',
    online_report_data_source_query : '/sys/dataSource/options',
    online_report_parse_sql: '/online/cgreport/head/parseSql',
    online_report_add : '/online/cgreport/head/add',
    online_report_edit : '/online/cgreport/head/editAll',
    online_report_items_query_by_id : 'online/cgreport/item/listByHeadId',
    online_report_params_query_by_id : 'online/cgreport/param/listByHeadId',
    online_report_delete : '/online/cgreport/head/deleteBatch',
    online_report_params_info_by_id : '/online/cgreport/api/getParamsInfo/',
    online_report_api_get_query_info : '/online/cgreport/api/getQueryInfo/',
    online_report_api_get_column_and_data : '/online/cgreport/api/getColumnsAndData/',
    online_report_api_export : '/online/cgreport/api/exportXls/',
    online_graph_query_list : '/online/graphreport/head/list',
    online_graph_query_fields_by_id : '/online/graphreport/head/queryOnlGraphreportItemByMainId',
    online_graph_add : '/online/graphreport/head/add',
    online_graph_edit : '/online/graphreport/head/edit',
    online_graph_delete : '/online/graphreport/head/deleteBatch',
    online_graph_export : '/online/graphreport/head/exportXls',
    online_graph_import : '/online/graphreport/head/importExcel',
    online_graph_get_char_data: '/online/graphreport/api/getChartsData',
}