export default {
    sys_common_dict : '/sys/dict/list',
    sys_common_dict_item : '/sys/dictItem/list',
    sys_common_upload : '/sys/common/upload',
    sys_user_query_list: '/sys/user/list',
    sys_user_change_pwd : '/sys/user/changPassword',
    sys_user_delete : '/sys/user/delete',
    sys_user_deleteBatch : '/sys/user/deleteBatch',
    sys_user_frozenBatch : '/sys/user/frozenBatch',
    sys_user_unique_user_check : '/sys/user/checkOnlyUser',
    sys_user_generate_user_id : '/sys/user/generateUserId',
    //sys_user_add_user_dept_ids : '/sys/user/addUDepartIds',
    sys_user_agent_user_info_query: '/system/sysUserAgent/queryByUserName',
    sys_user_edit_user_dept_ids : '/sys/user/editUDepartIds',
    sys_user_query_user_by_role : '/sys/user/userRoleList',
    sys_user_query_user_by_dept : '/sys/user/departUserList',
    sys_user_edit_dept_with_user : '/sys/user/editSysDepartWithUser',
    sys_user_delete_dept_user : '/sys/user/deleteUserInDepart',
    sys_user_delete_batch_dept_user : '/sys/user/deleteUserInDepartBatch',
    sys_user_export : '/sys/user/exportXls',
    sys_user_import : '/sys/user/importExcel',
    sys_user_add : '/sys/user/add',
    sys_user_edit : '/sys/user/edit',
    sys_role_query_all: '/sys/role/queryall',
    sys_role_query_user_role : '/sys/user/queryUserRole',
    sys_role_query_list : '/sys/role/list',
    sys_role_query_tree_list : '/sys/role/queryTreeList',
    sys_role_query_permission_by_role : '/sys/permission/queryRolePermission',
    sys_role_save_permission_by_role : '/sys/permission/saveRolePermission',
    sys_role_add_user_role : '/sys/user/addSysUserRole',
    sys_role_delete_user_role : '/sys/user/deleteUserRole',
    sys_role_delete_batch_user_role : '/sys/user/deleteUserRoleBatch',
    sys_role_data_rule : '/sys/role/datarule',
    sys_role_export : '/sys/role/exportXls',
    sys_role_import : '/sys/role/importExcel',
    sys_role_add : '/sys/role/add',
    sys_role_delete_batch : '/sys/role/deleteBatch',
    sys_role_update : '/sys/role/edit',
    sys_dept_query_all : '/sysdepart/sysDepart/queryTreeList',
    sys_dept_query_by_user : '/sys/user/userDepartList',
    sys_dept_add : '/sysdepart/sysDepart/add',
    sys_dept_edit : '/sysdepart/sysDepart/edit',
    sys_dept_export : '/sysdepart/sysDepart/exportXls',
    sys_dept_import : '/sysdepart/sysDepart/importExcel',
    sys_dept_delete_batch : '/sysdepart/sysDepart/deleteBatch',
    sys_dict_unique_check : '/sys/duplicate/check',
    sys_menu_query_list: '/sys/permission/list',
    sys_menu_delete_batch : '/sys/permission/deleteBatch',
    sys_menu_add : '/sys/permission/add',
    sys_menu_edit : '/sys/permission/edit',
    sys_menu_query_data_rule : '/sys/permission/queryPermissionRule',
    sys_menu_add_add_permission_rule: '/sys/permission/addPermissionRule',
    sys_menu_add_edit_permission_rule: '/sys/permission/editPermissionRule',
    sys_menu_add_delete_permission_rule: '/sys/permission/deletePermissionRule',
    sys_dict_query_list : '/sys/dict/list',
    sys_dict_add : '/sys/dict/add',
    sys_dict_edit : '/sys/dict/edit',
    sys_dict_delete : '/sys/dict/delete',
    sys_dict_export : '/sys/dict/exportXls',
    sys_dict_import : '/sys/dict/importExcel',
    sys_dict_item_add : '/sys/dictItem/add',
    sys_dict_item_edit : '/sys/dictItem/edit',
    sys_dict_item_delete : '/sys/dictItem/delete',
    sys_my_message_query_list : '/system/sysAnnouncementSend/getMyAnnouncementSend',
    sys_my_message_note_read_all : '/system/sysAnnouncementSend/readAll',
    sys_my_message_note_read_one : '/system/sysAnnouncementSend/editByAnntIdAndUserId',
    sys_sys_announcement_query_list: '/sys/annountCement/list',
    sys_sys_announcement_importExcel: '/sys/annountCement/importExcel',
    sys_sys_announcement_exportXls: '/sys/annountCement/exportXls',
    sys_sys_announcement_add: '/sys/annountCement/add',
    sys_sys_announcement_edit: '/sys/annountCement/edit',
    sys_sys_announcement_delete: '/sys/annountCement/delete',
    sys_sys_announcement_delete_batch: '/sys/annountCement/deleteBatch',
    sys_sys_announcement_release: '/sys/annountCement/doReleaseData',
    sys_sys_announcement_revoke: '/sys/annountCement/doReovkeData',
}
